project:
  type: website

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/
        text: Projects
      - href: about.qmd
        text: About

format:
  lumo-html: 
    logo:  # optional image file above the title, square
    github-repo: "https://github.com/erikemilsson"
    primary-color: "#2b3137" # github's secondary color from their color palette
    self-contained: true
    is-particlejs-enabled: false
    bg-image: "" # Optional image file for the header background

execute: 
  freeze: auto  
  cache: true
  echo: true

publish:
  - source: project
    netlify:
      - id: 8c016a7b-14ea-4784-89bf-d6bc7c062bef
        url: erikemilsson.com
        format: _extensions/lumo