project:
  type: website
  resources: 
    - projects/Eliminate/Copy of Sankey_B_2030.html
    - projects/Eliminate/Supply_and_Demand_Year_2030.html 

theme: cosmo

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/learning_projects.qmd
        text: Learning Projects
      - href: about.qmd
        text: More About Me

execute: 
  freeze: auto  
  cache: true
  echo: true

publish:
  - source: project
    netlify:
      - id: 8c016a7b-14ea-4784-89bf-d6bc7c062bef
        url: erikemilsson.com
        format: _extensions/lumo