---
title: "Microsoft Fabric EU Critical Raw Materials Learning Project"
title-block-banner: "#0275d8"
toc: True
---

In this project I use Microsoft Fabric to create dynamic custom visuals based on static data and reports from the European Commission's list of Critical Raw Materials (EU CRM). I also use annually updated Eurostat datasets to compare with the every-third-year updated EU CRM list datasets. 

These two approaches enable additional *and* fresher insights to be gained from the EU CRM list, which is at the heart of the EU Critical Raw Material strategy and legislation (EU CRM Regulation).

:::{.callout-note}
EU CRM measure and prioritize material resource use quantitatively and qualitatively through risks associated with each respective material, broken down into the main categories of:

1. Economic Importance
2. Supply Risk

Classical risk theory is used to calculate the overall risk for each material, based on the main categories which are, in turn, calculated using combinations of various indicators. See the EU CRM methdology document for how the indicators form the main categories [Link](https://op.europa.eu/en/publication-detail/-/publication/2d43b7e2-66ac-11e7-b2f2-01aa75ed71a1/language-en).
:::

## Understanding the Datasets

**EU Critical Raw Materials Data**

The data is currently published in pdfs on the [EU Commission's site for CRM](https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en). Using Excel's Power Query or Fabric's Data Factory to extract the data from the pdf's yields data with critical errors in the dataframe structures, e.g. mismatching columns and cell values. Additionally, the data is spread over several years and is not standardized, making future updates difficult to automate.

I explored the datasets while considering ways to effectively manage the data cleaning. The size of the datasets are relatively small and manageable, so I opted to get better control of the source data by combining Power Query with manual cleaning in Excel, and publishing to a [public github repository](https://github.com/erikemilsson/EU-Critical-Raw-Materials-CRM-Reports-Datasets) (while of course following the EU Commission's licensing requirements). This

- simplifies the data ingestion stage considerably,
- enables other analysts and developers to use the datasets and collaborate, 
- creates transparency in data cleaning, and
- tracks updates for future updates of the list through version control.

**Eurostat Data**

